"""added token id in user account

Revision ID: 61a766633424
Revises: b44190ea6cdb
Create Date: 2025-01-16 19:04:56.223425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a766633424'
down_revision = 'b44190ea6cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accountTokenId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_accountTokenId_token'), 'token', ['accountTokenId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_accountTokenId_token'), type_='foreignkey')
        batch_op.drop_column('accountTokenId')

    # ### end Alembic commands ###
