"""fifth  migration

Revision ID: 05cd96b4bd73
Revises: 429ed70b53f1
Create Date: 2024-11-03 23:02:19.250172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cd96b4bd73'
down_revision = '429ed70b53f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_level')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_level', sa.Enum('BASIC', 'PLATINUM', 'GOLD', name='membershiplevel'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('membership_level')

    op.create_table('membership_level',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('benefits', sa.TEXT(), nullable=True),
    sa.Column('cashback_bonus', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
